### ISSUE TITLE
多语言的话怎么加载

### ISSUE THREAD

**Issue by tgly307** [micro-structure/parent#1]
比如使用vue开发的话，子项目加载以前某些字段没有对应的翻译文本（比如菜单项），vue-i18n中的message文本虽然可以在加载了子模块后用方法动态修改，但是修改以后浏览器并不会重新渲染，原来缺失的字段还是不会更新显示，这个问题怎么解决比较好？

**Comment by Jmingzi** [comment]
@tgly307 抱歉，今天才能够回复你。这个问题我说说我的想法，并不能够提供给你可用的建议：子项目尽可能的只做子项目自己的事情，超过范围的应该交给主项目去做。比如国际化：多语言的文本配置项应该在主项目中，同时将`vue-i18n`实例通过 `window._MICRO_APP_CONFIG`暴露给子项目。

**Comment by tgly307** [comment]
感谢回复，我的使用场景是多个子项目独立开发部署，最后在运行时统一到主项目中，因此需要子项目自己完成多语言和路由之类的配置，主项目本身只引入了vue-i18n，没有具体的语言配置信息。不过后来我找到一个迂回的办法，在子项目初始化时将多语言配置通过window事件提交到主工程，主工程将这部分信息注册（i18n.mergeLocaleMessage）到多语言配置中。

**Comment by Jmingzi** [comment]
对的，是这种思路。路由就是这么干的，主项目提供空的容器实例，子项目去实例注册，需要注意的是，实例唯一，且实例内的命名空间。例如，我会将http请求分装成一个或多个实例在主项目中，然后子项目只需要注册url即可。
